<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <TargetFrameworks>net45;net7.0;net9.0;net10.0</TargetFrameworks>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <SuppressTfmSupportBuildErrors>true</SuppressTfmSupportBuildErrors>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)'=='net9.0' or '$(TargetFramework)'=='net10.0'">
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="NUnit" Version="4.4.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.0.1" />
  </ItemGroup>
  
  <ItemGroup Condition="'$(TargetFramework)'=='net7.0' or '$(TargetFramework)'=='net45'">
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.0.0" />
    <PackageReference Include="NUnit" Version="3.13.2" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.1.0" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)'=='net45'">
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GrobExp.Compiler\GrobExp.Compiler.csproj" />
  </ItemGroup>

</Project>
